### ISSUE TITLE
Remove apps from the list

### ISSUE THREAD

**Issue by pchettiy** [k0shk0sh/FastAccess#6]
Currently only apps can be added to fast access and reordered, but there is no way to remove them.

**Comment by k0shk0sh** [comment]
hello Prabakar, to delete an app simply click on any app and the click delete icon from the action mode. you can delete multiple apps at once if you want to, however by simply just clicking on an app in selected apps tab will show the action mode with an icon to select all or a trash icon. pls let me know if you have any more problems.

**Comment by k0shk0sh** [comment]
btw, please if that helps do revaluate your 3 star rating. and any suggestions or issues you have please post them here and i will be happy to review them. 
thanks

**Comment by k0shk0sh** [comment]
hello praba, could describe your second issue in here or open a new issue?
